/** Single source of truth for the home view, README table, and generated SKILL.md. */
export const COMMAND_TABLE: [need: string, command: string][] = [
  ["One of N options", 'jev-axi pick "<q>" --options a,b,c --state <file>'],
  ["Position on a rubric", 'jev-axi rate "<q>" --levels "low|mid|high" --state <file>'],
  ["Yes/no probability", 'jev-axi check "<statement>" --state <file>'],
  ["Many questions, one call", "jev-axi ask --questions <json> --state <file>"],
  ["Rank files or lines by a query", 'jev-axi rank "<query>" <paths|dir|->'],
  ["Keep items matching a predicate", 'jev-axi filter "<predicate>" <paths|->'],
  ["Semantic grep in one file", 'jev-axi find "<question>" <file>'],
  ["Which files a task touches", 'jev-axi files "<task>" [dirs]'],
  ["Review a diff before committing", "jev-axi diff --staged"],
  ["Triage a build or test log", "<cmd> 2>&1 | jev-axi triage"],
  ["Screen untrusted text (exit 3 = block)", "curl ... | jev-axi guard"],
  ["Is the job done? Diff and test output vs the task", 'jev-axi progress --job "<task>"'],
  ["Warn when an agent stops early, gets stuck, or drifts", "jev-axi setup supervise [--project]"],
  ["Block risky agent tool calls before they run", "jev-axi setup safety [--project]"],
  ["Safety-check a shell command, then run it", "jev-axi guard-exec -- \"<command>\""],
  ["Block commits that add credentials; review staged diffs", "jev-axi setup git-hooks"],
  ["Give Claude Code an explorer subagent that uses jev-axi", "jev-axi setup agent [--project]"],
  ["Check commit messages against diffs", "jev-axi commit --range main..HEAD"],
  ["Saved question sets (YAML)", "jev-axi recipe list | run <name> | new <name>"],
  ["Tokens and spend, recent", "jev-axi usage [--by day|command|project]"],
  ["Lifetime stats and trends", "jev-axi stats [--days N]"],
  ["Show or clear the response cache", "jev-axi cache [clear [--stale]]"],
];

